export const pricing = [
  {
    id: "0",
    title: "Free",
    description: "AI chatbot, personalized recommendations",
    price: "0",
    buttonTitle: "Get Started For Free",
    features: [
      "Up to 5 project members",
      "Unlimited tasks and projects",
      "2GB storage",
      "Integrations",
      "Basic support",
    ],
  },
  {
    id: "1",
    title: "Pro",
    description: "Advanced AI chatbot, priority support, analytics dashboard",
    price: "9.99",
    buttonTitle: "Sign Up Now",
    features: [
      "Up to 50 project members",
      "Unlimited tasks and projects",
      "50GB storage",
      "Integrations",
      "Priority support",
      "Advanced support",
      "Export support",
    ],
  },
  {
    id: "2",
    title: "Business",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: "19.99",
    buttonTitle: "Sign Up Now",
    features: [
      "Up to 5 project members",
      "Unlimited tasks and projects",
      "200GB storage",
      "Integrations",
      "Dedicated account manager",
      "Custom fields",
      "Advanced analytics",
      "Export capabilities",
      "API access",
      "Advanced security features",
    ],
  },
];
